apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfuture-deployment-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gpitfuture-app-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfuture-api
        image: gpitfutureaksdev.azurecr.io/nhsd/buying-catalogue-api
        ports:
        - containerPort: 5100
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
        env:
        - name: ASPNETCORE_ENVIRONMENT 
          value: "Development"    
---        
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 5100
  selector:
    app: gpitfuture-app-api
---