version: '3.5'

services:

  db:
    image: integration_db:test
    container_name: integration_db
    networks:
      - integration_network
    ports:
      - "1433:1433"

  nhsd.buyingcatalogue.api:
    container_name: integration_api
    build: 
      context: .
      dockerfile: Dockerfile.integration
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings:BuyingCatalogue=Server=db;Initial Catalog=gpitfuture-db-dev;Persist Security Info=False;User Id=NHSD;Password=DisruptTheMarket1!
    networks:
      - integration_network
    depends_on:
      - db
    ports:
      - "8080:80"

networks: 
  integration_network:
    name: integration_network
    driver: bridge
