version: '3.5'

services:

  nhsd.buyingcatalogue.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings:Server=tcp:gpitfuture-sql-dev.database.windows.net,1433;Initial Catalog=gpitfuture-db-dev1;Persist Security Info=False;User ID=gpitfutureadmin;Password=Apguvltjcsamqyobnrxwfehdzk3750pk;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    network_mode: bridge
    ports:
      - "80:80"