version: '3.5'

services:

  nhsd.buyingcatalogue.api:
    image: ${REGISTRY:-nhsd}/buying-catalogue/api:${TAG:-latest}
    container_name: nhsd_bcapi
    build:
      context: .
      dockerfile: Dockerfile
    