version: '3.5'

services:

  nhsd.buyingcatalogue.api:
    image: ${REGISTRY:-nhsd}/buying-catalogue-api:${TAG:-latest}
    container_name: nhsd_bcapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings:BuyingCatalogue=${NHSD_BUYINGCATALOGUE_DB:-Data Source=db;Initial Catalog=buyingcatalogue;MultipleActiveResultSets=True;User Id=sa;Password=MyTestPassword123!}
    networks:
      - nhsd_bcnetwork
    ports:
      - "8080:80"

networks:
  nhsd_bcnetwork:
    name: nhsd_bcnetwork
    driver: bridge

volumes:
  nhsd_bcvolume:
    name: nhsd_bcvolume